{{ if .Values.lidarr.enabled }}
---
# SERVICE ACCOUNT & RBAC for Lidarr
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lidarr-sa
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lidarr-role
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lidarr-rolebinding
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lidarr-role
subjects:
- kind: ServiceAccount
  name: lidarr-sa
---
### CONFIGMAPS
## INIT-CONTAINER
apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>{{ .Values.lidarr.ingress.path }}</UrlBase>
    </Config>
  init-lidarr.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /lidarr-config/config.xml ]; then
      cp -n /init-lidarr/config.xml /lidarr-config/config.xml
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-lidarr-cm
---
## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: lidarr-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8 }}
        app: lidarr
    spec:
      serviceAccountName: lidarr-sa
      initContainers:
        - name: config-lidarr
          image: docker.io/ubuntu:groovy
          command: ["/init-lidarr/init-lidarr.sh"]
          volumeMounts:
            - mountPath: /init-lidarr
              name: init-files-lidarr
          {{- if .Values.lidarr.volume }}
            - name: {{ .Values.lidarr.volume.name }}
              mountPath: /lidarr-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /lidarr-config
              subPath: "{{ .Values.general.storage.subPaths.config }}/lidarr"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: lidarr-config
          image: "lscr.io/linuxserver/lidarr:latest"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "{{ .Values.lidarr.ingress.path }}/ping"
              port: {{ .Values.lidarr.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 20
          ports:
            - name: lidarr-port
              containerPort: {{ .Values.lidarr.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.lidarr.volume }}
            - name: {{ .Values.lidarr.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.general.storage.subPaths.config }}/lidarr"
          {{- end }}
          {{- with .Values.lidarr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.lidarr.extraContainers }}
        {{- toYaml .Values.lidarr.extraContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.lidarr.tolerations }}
      tolerations:
        {{- toYaml .Values.lidarr.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        {{ if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{- if .Values.lidarr.volume }}
        - name: {{ .Values.lidarr.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.lidarr.volume.name }}
        {{- end }}
        - name: init-files-lidarr
          configMap:
            defaultMode: 493
            name: init-lidarr-cm
        {{- if .Values.lidarr.extraContainers }}
          {{- toYaml .Values.lidarr.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with merge .Values.lidarr.container.nodeSelector .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io: {{ .Release.Name }}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lidarr.service.type }}
  ports:
    - port: {{ .Values.lidarr.service.port }}
      targetPort: {{ .Values.lidarr.container.port }}
      protocol: TCP
{{ if eq .Values.lidarr.service.type "NodePort" }}
      nodePort: {{ .Values.lidarr.service.nodePort }}
{{ end }}
      name: lidarr-port
  selector:
    app: lidarr

---
{{ if .Values.lidarr.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: lidarr-lb
  {{- with .Values.lidarr.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.lidarr.service.port }}
      targetPort: {{ .Values.lidarr.container.port }}
      protocol: TCP
      name: lidarr-port
  selector:
    app: lidarr
{{ end }}
---
### INGRESS ###
{{ if .Values.lidarr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.lidarr.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.lidarr.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.lidarr.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.lidarr.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: {{ .Values.lidarr.service.port }}
{{ end }}
{{ end }} 